- hosts: centoservers
  tasks:

    - name: installing some necessarily packages
      yum: 
        name: "{{ packages }}" 
      vars:
        packages:
         - yum-utils
         - device-mapper-persistent-data
         - lvm2
      update_cache: yes
      state: present

    - name: Add repository docker
      yum_repository:
        name: docker-ce
        description: Docker CE stable
        baseurl:  https://download.docker.com/linux/centos/7/$basearch/stable
        gpgkey: https://download.docker.com/linux/centos/gpg
        gpgcheck: yes
        enabled: yes

    - name: install docker 
      yum: 
        name: "{{ packages }}" 
      vars:
        packages:
          - docker-ce 
          - docker-ce-cli 
          - containerd.io
      update_cache: yes
      state: present